# Service ClusterIP for Gateway
apiVersion: v1
kind: Service
metadata:
  name: iot-gateway-clusterip
  namespace: project
spec:
  selector:
    app: iot-gateway
  ports:
  - protocol: TCP
    name: http    
    port: 8081
    targetPort: 8081
  type: ClusterIP
